
  
  window.webSnake = {};

  window.webSnake.urlMap = [
  {
    "oldUrl": "https://www.google.com/xjs/_/js/k=xjs.s.en_GB.kjO0EDjOYyE.2018.O/ck=xjs.s.tWGBBDf-ZD4.L.B1.O/am=AMIhgBAAAAAIAAAAIQBUAAIAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAABAAAAAAAAgAAAGAuiIIBSPgEAAAAQnBQAsgMAAAAAH8AjThWAAgAAAwKAgCABAAAAAgACAAIAYAIIQCBkAQAoACAghBAAIACACQAAEAECIhLs978GBgAAGQAAAAAIAFRSAHGQAAQAcAAAwBEXAiQCMABCdwEJAABACQEAACAAACgAAAAgAACAEKAcgmEABBUABnAEAAAAADIAQCAAAAAIBAgBADAAoBAAECAAAPQAgAB8AABAAkQAACgAAxgBACAAJPDDBgAEAADgJAAAgACgBAAOIwyAAAAAAAAAAOQB4PEAGFJQAAAAAAAAAAAAAAAAIAAJgjmQfkEAAQAAAAAAAAAAAAAAAAAASBE0ca0BAAI/d=0/dg=0/br=1/ujg=1/rs=ACT90oGNUCfyImvKyNhE6U21KlCbASYzvA/m=syhq,aLUfP,wQlYve,sy8ee,sy42k,sy442,sy8dy,sy8dx,sy5p1,sy1ms,sy1mk,sy82,sy1ml,sysl,pKhWu,sy7ln,pHXghd?xjs=s3",
    "newUrl": "snake.js"
  }
];
  
  window.webSnake.blockedUrls = [
  "https://www.google.com/async/bgasy?ei=ssfdZ9LFOL61hbIP68LN-QI&opi=89978449&yv=3&cs=0&async=_fmt:jspb",
  "https://www.google.com/xjs/_/js/k=xjs.s.en_GB.kjO0EDjOYyE.2018.O/am=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAigIAACAAAAAAAAAAQAAgAAAAAAAEACAAAAAAAAAwKAgCABAAAAAgAAAAAAYAIAQCBgAQAoAAAAAAAAAAAACAAAAAACIgLs958GAAAAAAAAAAAAAAAAAAGQAAAAMAAAAAAXAAACMABCdgEBAAAAAAAAACAAAAAAAAAgAAAAACAAAgAAABQAAAAAAAAAABAAAAAAAAAABAAAABAAABAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAABPADAAAAAADgAAAAgAAAAAAOIwyAAAAAAAAAAOQB4PEAGFJQAAAAAAAAAAAAAAAAIAAJgjmQfkEAAQAAAAAAAAAAAAAAAAAASBE0ca0BAAI/d=0/dg=0/br=1/rs=ACT90oHW2pwD2Zgtkm4oa3QIPzU6cIx7JQ/m=sb_wiz,aa,abd,U9EYge,sysk,sysj,syse,syhs,sysi,sys5,sy15x,syxf,syst,sysr,sysa,syxe,syx7,syta,sysd,sysw,syso,sysm,sys7,syxd,sysf,sysg,sysh,sysp,sys1,sys9,syxg,syt9,syt8,syt7,async,sy18i,bgd,sy8a5,foot,sy27m,kyn,sy16f,sy2dp,lli,sf,sy17z,sy180,sy7s8,sonic,sy7y9,sy1oa,syh0,sy3r9,sy17p,sy16q,sy140,syux,syy1,syxz,syxy,syxw,syxv,syy0,sy1vs,sy1vt,sy13z,syyc,sybg,syaa,sya9,sya8,sya7,spch,tl?xjs=s4"
];
  
  